[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/model/*"
  to = "https://demo.infra.opencost.io/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
