// Mock asset data for development/testing without a backend
// Used automatically when the backend is unavailable

const now = new Date();
const dayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const startISO = dayAgo.toISOString();
const endISO = now.toISOString();

export const getMockAssetData = () => {
  return {
    code: 200,
    data: {
      "cluster1/node/gke-prod-pool-1": {
        type: "Node",
        properties: {
          cluster: "cluster1",
          name: "gke-prod-pool-1",
          providerID: "gce://my-project/us-central1-a/gke-prod-pool-1",
          category: "Compute",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {
          "node.kubernetes.io/instance-type": "e2-standard-4",
          "topology.kubernetes.io/zone": "us-central1-a",
          "cloud.google.com/gke-nodepool": "default-pool",
        },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        nodeType: "e2-standard-4",
        cpuCores: 4,
        ramBytes: 17179869184,
        cpuCost: 2.88,
        ramCost: 1.54,
        gpuCost: 0,
        cpuBreakdown: { idle: 0.35, system: 0.15, user: 0.45, other: 0.05 },
        ramBreakdown: { idle: 0.25, system: 0.1, user: 0.55, other: 0.1 },
        preemptible: 0,
        discount: 0.3,
        totalCost: 4.42,
      },
      "cluster1/node/gke-prod-pool-2": {
        type: "Node",
        properties: {
          cluster: "cluster1",
          name: "gke-prod-pool-2",
          providerID: "gce://my-project/us-central1-b/gke-prod-pool-2",
          category: "Compute",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {
          "node.kubernetes.io/instance-type": "e2-standard-8",
          "topology.kubernetes.io/zone": "us-central1-b",
          "cloud.google.com/gke-nodepool": "high-mem-pool",
        },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        nodeType: "e2-standard-8",
        cpuCores: 8,
        ramBytes: 34359738368,
        cpuCost: 5.76,
        ramCost: 3.08,
        gpuCost: 0,
        cpuBreakdown: { idle: 0.55, system: 0.1, user: 0.3, other: 0.05 },
        ramBreakdown: { idle: 0.4, system: 0.08, user: 0.42, other: 0.1 },
        preemptible: 0,
        discount: 0.3,
        totalCost: 8.84,
      },
      "cluster1/node/gke-prod-pool-3": {
        type: "Node",
        properties: {
          cluster: "cluster1",
          name: "gke-prod-pool-3",
          providerID: "gce://my-project/us-central1-c/gke-prod-pool-3",
          category: "Compute",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {
          "node.kubernetes.io/instance-type": "n1-standard-4",
          "topology.kubernetes.io/zone": "us-central1-c",
          "cloud.google.com/gke-nodepool": "default-pool",
          "cloud.google.com/gke-accelerator": "nvidia-tesla-t4",
        },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        nodeType: "n1-standard-4",
        cpuCores: 4,
        ramBytes: 15728640000,
        cpuCost: 3.12,
        ramCost: 1.68,
        gpuCost: 12.5,
        cpuBreakdown: { idle: 0.2, system: 0.12, user: 0.6, other: 0.08 },
        ramBreakdown: { idle: 0.15, system: 0.1, user: 0.65, other: 0.1 },
        preemptible: 1,
        discount: 0.6,
        totalCost: 17.3,
      },
      "cluster2/node/eks-workers-1": {
        type: "Node",
        properties: {
          cluster: "cluster2",
          name: "eks-workers-1",
          providerID: "aws:///us-east-1a/i-0abcdef1234567890",
          category: "Compute",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: {
          "node.kubernetes.io/instance-type": "m5.xlarge",
          "topology.kubernetes.io/zone": "us-east-1a",
          "eks.amazonaws.com/nodegroup": "workers",
        },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        nodeType: "m5.xlarge",
        cpuCores: 4,
        ramBytes: 17179869184,
        cpuCost: 2.76,
        ramCost: 1.8,
        gpuCost: 0,
        cpuBreakdown: { idle: 0.45, system: 0.08, user: 0.45, other: 0.02 },
        ramBreakdown: { idle: 0.5, system: 0.06, user: 0.43, other: 0.01 },
        preemptible: 0,
        discount: 0.15,
        totalCost: 4.56,
      },
      "cluster2/node/eks-workers-2": {
        type: "Node",
        properties: {
          cluster: "cluster2",
          name: "eks-workers-2",
          providerID: "aws:///us-east-1b/i-0abcdef9876543210",
          category: "Compute",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: {
          "node.kubernetes.io/instance-type": "m5.2xlarge",
          "topology.kubernetes.io/zone": "us-east-1b",
          "eks.amazonaws.com/nodegroup": "workers",
        },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        nodeType: "m5.2xlarge",
        cpuCores: 8,
        ramBytes: 34359738368,
        cpuCost: 5.12,
        ramCost: 2.8,
        gpuCost: 0,
        cpuBreakdown: { idle: 0.28, system: 0.1, user: 0.6, other: 0.02 },
        ramBreakdown: { idle: 0.32, system: 0.07, user: 0.6, other: 0.01 },
        preemptible: 0,
        discount: 0.15,
        totalCost: 7.92,
      },
      "cluster1/disk/pvc-abc123": {
        type: "Disk",
        properties: {
          cluster: "cluster1",
          name: "pvc-abc123",
          providerID: "gce://my-project/us-central1-a/pvc-abc123",
          category: "Storage",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        storageClass: "standard",
        volumeName: "pvc-abc123",
        claimName: "data-postgres-0",
        claimNamespace: "production",
        bytes: 107374182400,
        byteHours: 2576980377600,
        breakdown: { idle: 0.4, system: 0, user: 0.6, other: 0 },
        totalCost: 1.2,
      },
      "cluster1/disk/pvc-def456": {
        type: "Disk",
        properties: {
          cluster: "cluster1",
          name: "pvc-def456",
          providerID: "gce://my-project/us-central1-b/pvc-def456",
          category: "Storage",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        storageClass: "ssd",
        volumeName: "pvc-def456",
        claimName: "data-redis-0",
        claimNamespace: "production",
        bytes: 53687091200,
        byteHours: 1288490188800,
        breakdown: { idle: 0.7, system: 0, user: 0.3, other: 0 },
        totalCost: 2.4,
      },
      "cluster2/disk/pvc-ghi789": {
        type: "Disk",
        properties: {
          cluster: "cluster2",
          name: "pvc-ghi789",
          providerID: "vol-0abcdef1234",
          category: "Storage",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        storageClass: "gp3",
        volumeName: "pvc-ghi789",
        claimName: "prometheus-data",
        claimNamespace: "monitoring",
        bytes: 214748364800,
        byteHours: 5153960755200,
        breakdown: { idle: 0.25, system: 0, user: 0.75, other: 0 },
        totalCost: 3.1,
      },
      "cluster1/loadbalancer/ingress-nginx": {
        type: "LoadBalancer",
        properties: {
          cluster: "cluster1",
          name: "ingress-nginx",
          providerID: "gce://my-project/us-central1/ingress-nginx",
          category: "Network",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: { service: "ingress-nginx-controller", namespace: "ingress-nginx" },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 0.6,
      },
      "cluster2/loadbalancer/api-gateway": {
        type: "LoadBalancer",
        properties: {
          cluster: "cluster2",
          name: "api-gateway",
          providerID: "arn:aws:elasticloadbalancing:us-east-1:123:loadbalancer/net/api-gw/abc",
          category: "Network",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: { service: "api-gateway", namespace: "production" },
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 1.08,
      },
      "cluster1/network/__network__": {
        type: "Network",
        properties: {
          cluster: "cluster1",
          name: "cluster1-network",
          providerID: "cluster1-network",
          category: "Network",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 0.36,
      },
      "cluster2/network/__network__": {
        type: "Network",
        properties: {
          cluster: "cluster2",
          name: "cluster2-network",
          providerID: "cluster2-network",
          category: "Network",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 0.54,
      },
      "cluster1/management/__management__": {
        type: "ClusterManagement",
        properties: {
          cluster: "cluster1",
          name: "cluster1-management",
          providerID: "cluster1-management",
          category: "Management",
          provider: "GCP",
          project: "my-gcp-project",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 2.4,
      },
      "cluster2/management/__management__": {
        type: "ClusterManagement",
        properties: {
          cluster: "cluster2",
          name: "cluster2-management",
          providerID: "cluster2-management",
          category: "Management",
          provider: "AWS",
          project: "aws-account-123",
        },
        labels: {},
        window: { start: startISO, end: endISO },
        start: startISO,
        end: endISO,
        minutes: 1440,
        totalCost: 3.6,
      },
    },
  };
};
