// Enhanced mock data with more diverse assets for testing
export const mockAssetsData = {
    code: 200,
    data: [
        {
            ClusterManagement: {
                type: "ClusterManagement",
                properties: {
                    category: "Management",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                },
                labels: {
                    "cost-center": "platform",
                    "environment": "production",
                    namespace: "kube-system",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-25T00:00:00Z",
                minutes: 10080.0,
                totalCost: 24.50,
            },
            "Node-prod-1": {
                type: "Node",
                properties: {
                    category: "Compute",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                    name: "gke-prod-node-1",
                },
                labels: {
                    "cost-center": "engineering",
                    "environment": "production",
                    namespace: "default",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                nodeType: "e2-standard-4",
                cpuCores: 4.0,
                ramBytes: 16106127360,
                cpuCoreHours: 644.67,
                ramByteHours: 2592985251840,
                GPUHours: 0.0,
                cpuBreakdown: {
                    idle: 0.65,
                    other: 0.02,
                    system: 0.08,
                    user: 0.25,
                },
                ramBreakdown: {
                    idle: 0.72,
                    other: 0,
                    system: 0.03,
                    user: 0.25,
                },
                preemptible: 0.0,
                discount: 0.15,
                cpuCost: 45.50,
                gpuCost: 0.0,
                gpuCount: 0.0,
                ramCost: 22.30,
                adjustment: -8.20,
                totalCost: 59.60,
            },
            "Node-prod-2": {
                type: "Node",
                properties: {
                    category: "Compute",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                    name: "gke-prod-node-2",
                },
                labels: {
                    "cost-center": "engineering",
                    "environment": "production",
                    namespace: "default",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                nodeType: "e2-standard-8",
                cpuCores: 8.0,
                ramBytes: 32212254720,
                cpuCoreHours: 1289.33,
                ramByteHours: 5185970503680,
                GPUHours: 0.0,
                cpuBreakdown: {
                    idle: 0.45,
                    other: 0.03,
                    system: 0.12,
                    user: 0.40,
                },
                ramBreakdown: {
                    idle: 0.38,
                    other: 0,
                    system: 0.07,
                    user: 0.55,
                },
                preemptible: 0.0,
                discount: 0.20,
                cpuCost: 91.00,
                gpuCost: 0.0,
                gpuCount: 0.0,
                ramCost: 44.60,
                adjustment: -18.40,
                totalCost: 117.20,
            },
            "Disk-boot": {
                type: "Disk",
                properties: {
                    category: "Storage",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                    name: "persistent-disk-boot",
                },
                labels: {
                    "cost-center": "infrastructure",
                    namespace: "kube-system",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                byteHours: 80541516519424.0,
                bytes: 107374182400, // 100GB
                byteHoursUsed: 32216606607769.6,
                byteUsageMax: null,
                breakdown: {
                    idle: 0.60,
                    other: 0,
                    system: 0.10,
                    user: 0.30,
                },
                adjustment: -2.10,
                totalCost: 8.40,
                storageClass: "pd-standard",
                volumeName: "pvc-boot-volume",
                claimName: "",
                claimNamespace: "",
            },
            "Disk-data": {
                type: "Disk",
                properties: {
                    category: "Storage",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                    name: "persistent-disk-data",
                },
                labels: {
                    "cost-center": "data",
                    namespace: "databases",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                byteHours: 322122547200.0,
                bytes: 536870912000, // 500GB
                byteHoursUsed: 289910292480,
                byteUsageMax: null,
                breakdown: {
                    idle: 0.10,
                    other: 0,
                    system: 0.05,
                    user: 0.85,
                },
                adjustment: -4.50,
                totalCost: 35.80,
                storageClass: "pd-ssd",
                volumeName: "pvc-postgresql-data",
                claimName: "postgres-data-claim",
                claimNamespace: "databases",
            },
            LoadBalancer: {
                type: "LoadBalancer",
                properties: {
                    category: "Network",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                    name: "ingress-nginx/ingress-controller",
                    providerID: "35.202.154.180",
                },
                labels: {
                    "cost-center": "platform",
                    namespace: "ingress-nginx",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                adjustment: 0.0,
                totalCost: 18.20,
            },
            Network: {
                type: "Network",
                properties: {
                    category: "Network",
                    provider: "GCP",
                    project: "production-cluster",
                    service: "Kubernetes",
                    cluster: "cluster-prod-us",
                },
                labels: {
                    "cost-center": "platform",
                    "goog-k8s-cluster-location": "us-central1-a",
                    "goog-k8s-cluster-name": "cluster-prod-us",
                    namespace: "kube-system",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-23T00:00:00Z",
                minutes: 7200.0,
                adjustment: -0.0,
                totalCost: 12.45,
            },
            "GPU-Node": {
                type: "Node",
                properties: {
                    category: "Compute",
                    provider: "GCP",
                    project: "ml-training",
                    service: "Kubernetes",
                    cluster: "cluster-ml-us",
                    name: "gke-ml-gpu-node",
                },
                labels: {
                    "cost-center": "ml-platform",
                    "environment": "production",
                    namespace: "ml-training",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 4800.0, // only ran for ~80 hours
                nodeType: "n1-standard-8-nvidia-tesla-t4",
                cpuCores: 8.0,
                ramBytes: 30064771072,
                cpuCoreHours: 640.0,
                ramByteHours: 2405181685760,
                GPUHours: 80.0,
                cpuBreakdown: {
                    idle: 0.85, // High idle - expensive underutilized GPU node
                    other: 0.01,
                    system: 0.04,
                    user: 0.10,
                },
                ramBreakdown: {
                    idle: 0.90,
                    other: 0,
                    system: 0.02,
                    user: 0.08,
                },
                preemptible: 0.0,
                discount: 0.0,
                cpuCost: 32.00,
                gpuCost: 280.00,
                gpuCount: 1.0,
                ramCost: 15.20,
                adjustment: 0.0,
                totalCost: 327.20,
            },
            "AWS-Node-staging": {
                type: "Node",
                properties: {
                    category: "Compute",
                    provider: "AWS",
                    project: "staging-env",
                    service: "EKS",
                    cluster: "cluster-staging-east",
                    name: "eks-staging-node-1",
                },
                labels: {
                    "cost-center": "engineering",
                    "environment": "staging",
                    namespace: "default",
                },
                window: {
                    start: "2023-07-18T00:00:00Z",
                    end: "2023-07-25T00:00:00Z",
                },
                start: "2023-07-18T00:00:00Z",
                end: "2023-07-24T17:10:00Z",
                minutes: 9670.0,
                nodeType: "m5.large",
                cpuCores: 2.0,
                ramBytes: 8589934592,
                cpuCoreHours: 322.33,
                ramByteHours: 1382296985600,
                GPUHours: 0.0,
                cpuBreakdown: {
                    idle: 0.55,
                    other: 0.02,
                    system: 0.08,
                    user: 0.35,
                },
                ramBreakdown: {
                    idle: 0.48,
                    other: 0,
                    system: 0.05,
                    user: 0.47,
                },
                preemptible: 0.0,
                discount: 0.10,
                cpuCost: 18.50,
                gpuCost: 0.0,
                gpuCount: 0.0,
                ramCost: 9.20,
                adjustment: -2.80,
                totalCost: 24.90,
            },
        },
    ],
};
