name: 'Build Container'
description: 'Build and publish OpenCost UI container image'

inputs:
  actor:
    description: 'GitHub actor'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  image_tag:
    description: 'Full image tag to use for the container'
    required: true
  release_version:
    description: 'Release version for the container'
    required: true
  registry:
    description: 'Container registry to use'
    required: true
    default: 'ghcr.io'

runs:
  using: "composite"
  steps:
    - name: Log into registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
      shell: bash

    - name: Set up just
      uses: extractions/setup-just@v3
      shell: bash

    - name: Install crane
      uses: imjasonh/setup-crane@v0.3
      shell: bash

    - name: Install manifest-tool
      run: |
        mkdir -p manifest-tool
        pushd manifest-tool
        wget -q https://github.com/estesp/manifest-tool/releases/download/v2.0.8/binaries-manifest-tool-2.0.8.tar.gz
        tar -xzf binaries-manifest-tool-2.0.8.tar.gz
        cp manifest-tool-linux-amd64 manifest-tool
        echo "$(pwd)" >> $GITHUB_PATH
      shell: bash

    - name: Build and push (multiarch)
      env:
        IMAGE_TAG: ${{ inputs.image_tag }}
        RELEASE_VERSION: ${{ inputs.release_version }}
      run: |
        just build "$IMAGE_TAG" "$RELEASE_VERSION"
      shell: bash 